@FirstApi_HostAddress = http://localhost:5246
@email = adeniyidamilola246@gmail.com
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkJlYXJlciJ9.eyJuYW1laWQiOiIxIiwiZW1haWwiOiJqb2huQGV4YW1wbGUuY29tIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsIm5iZiI6MTc3NTMzNzMxOCwiZXhwIjoxNzc1MzQwOTE4LCJpYXQiOjE3NzUzMzczMTgsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjcwMDAiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo3MDAwIn0.jXwStNCcDs7ajaPDZizHNahWZlC09SzfrIRFsl8qZ_k
GET {{FirstApi_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{FirstApi_HostAddress}}/
Accept: application/json

###

GET {{FirstApi_HostAddress}}/api/books
Accept: application/json
Authorization: Bearer {{token}}

###

GET {{FirstApi_HostAddress}}/api/books/1
Accept: application/json
Authorization: Bearer {{token}}

###
POST {{FirstApi_HostAddress}}/api/books
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Book 2",
    "author": "Author 3",
    "yearPublished": 2200
}

###
PUT {{FirstApi_HostAddress}}/api/books/6
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Book 13",
    "author": "Author 13",
    "yearPublished": 2032
}

###
DELETE {{FirstApi_HostAddress}}/api/books/6
Accept: application/json
Authorization: Bearer {{token}}

###
POST {{FirstApi_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "firstName": "James",
  "lastName": "Does",
  "email":"adeniyidamilola38@gmail.com",
  "password": "Test123!"
}

###
POST {{FirstApi_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "john@example.com",
  "password": "Password123!"
}

###
POST {{FirstApi_HostAddress}}/api/auth/forgot-password
Content-Type: application/json

{
    "email": "[EMAIL_ADDRESS]"
}

###
POST {{FirstApi_HostAddress}}/api/auth/resend-email-verification-token
Content-Type: application/json

{
    "email": "adeniyidamilola38@gmail.com"
}

###
POST {{FirstApi_HostAddress}}/api/auth/reset-password
Content-Type: application/json

{
    "email": "[EMAIL_ADDRESS]",
    "token": "",
    "password": "Password123!"
}

###
POST {{FirstApi_HostAddress}}/api/auth/verify-email
Content-Type: application/json

{
    "email": "adeniyidamilola38@gmail.com",
    "token": "7598"
}